# Generated by Django 4.0.3 on 2022-04-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('alias', models.CharField(default='!!!', max_length=64, unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('alias', models.CharField(default='!!!', max_length=64, unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Праздник')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата')),
                ('alias', models.CharField(default='!!!', max_length=64, unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Праздеик',
                'verbose_name_plural': 'Праздники',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('alias', models.CharField(default='!!!', max_length=64, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=0, verbose_name='Остаток')),
                ('popular', models.IntegerField(default=0, verbose_name='Популярность')),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('article', models.CharField(blank=True, default=None, max_length=8, verbose_name='Артикль')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория')),
                ('holiday', models.ManyToManyField(default='1', to='product.holiday', verbose_name='Праздник')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/')),
                ('active', models.BooleanField(default=True)),
                ('main', models.BooleanField(default=False, verbose_name='Главная')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='product.product')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.department'),
        ),
    ]
